directive @isAuthenticated on FIELD_DEFINITION

type Book {
  id: ID!
  name: String!
  genre: String!
  author: Author!
  authorId: ID!
}

type Author {
  id: ID!
  age: Int!
  name: String!
  gender: String!
  email: String!
  about: String
  books: [Book]
}

type Column {
  id: ID!
  name: String!
  cards: [Card]
}

type Card {
  id: ID!
  client: String!
  reference: String!
  description: String!
  tier: String
  columnId: String
}

type User {
  id: ID!
  email: String!
  password: String!
  jwt: String
}

type Query {
  Author(id: ID!): Author @isAuthenticated
  Book(id: ID!): Book @isAuthenticated
  Card(id: ID!): Card @isAuthenticated
  Column(id: ID!): Column @isAuthenticated
  User(id: ID!): User @isAuthenticated
  Authors: [Author] @isAuthenticated
  Books: [Book] @isAuthenticated
  Cards: [Card] @isAuthenticated
  cards: [Card] @isAuthenticated
  Columns: [Column] @isAuthenticated
  me: User @isAuthenticated
}

type Mutation {
  addAuthor(age: Int!, name: String!, gender: String!, email: String!, about: String): Author @isAuthenticated
  addBook(name: String!, genre: String!, authorId: String!): Book @isAuthenticated
  addCard(client: String!, reference: String!, description: String!, tier: String, columnId: String): Card
    @isAuthenticated
  addColumn(name: String!): Column @isAuthenticated
  signup(email: String!, password: String!): User
  login(email: String!, password: String!): User
}
