directive @isAuthenticated on FIELD_DEFINITION

type Column {
  id: ID!
  name: String!
  cards: [Card]
  userID: ID!
}

type Card {
  id: ID!
  client: String!
  reference: String!
  description: String!
  tier: String
  columnId: String
}

type User {
  id: ID!
  email: String!
  password: String!
  jwt: String
  columns: [Column]
}

type Query {
  Card(id: ID!): Card @isAuthenticated
  Column(id: ID!): Column @isAuthenticated
  User(id: ID!): User @isAuthenticated
  Cards: [Card] @isAuthenticated
  Columns: [Column] @isAuthenticated
  userColumns(userID: ID!): [Column] @isAuthenticated
  me: User @isAuthenticated
}

type Mutation {
  addCard(client: String!, reference: String!, description: String!, tier: String, columnId: String): Card
    @isAuthenticated
  addColumn(name: String!, userID: ID!): Column @isAuthenticated
  signup(email: String!, password: String!): User
  login(email: String!, password: String!): User
}
